# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
# $ cloud-build-local --config=cloudbuild.yaml --dryrun=false .

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

# - name: 'gcr.io/cloud-builders/gcloud'
#   args: 
#   - firebase
#   - use
#   - default

# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['firebase use',  'default']

# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['firebase', 'deploy',  '--only hosting']
